# Generated by Django 5.1.6 on 2025-02-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electronic_platform", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="supplier",
            old_name="supplier_type",
            new_name="provider_type",
        ),
        migrations.AddField(
            model_name="supplier",
            name="level",
            field=models.IntegerField(default=1, verbose_name="Уровень в иерархии"),
        ),
    ]
