# Generated by Django 5.1.6 on 2025-02-23 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "electronic_platform",
            "0002_rename_supplier_type_supplier_provider_type_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="supplier",
            new_name="provider",
        ),
    ]
